# Generated by Django 5.2.7 on 2025-11-13 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('name', models.CharField(choices=[('МИНОН', 'МИНОН'), ('МИНИМИНОН', 'МИНИМОНОН'), ('КУЛИЧ', 'КУЛИЧ'), ('МИНЬЁН', 'МИНЬЁН')], default='МИНОН', max_length=50, verbose_name='Название уровня')),
            ],
            options={
                'verbose_name': 'Уровень подписки',
                'verbose_name_plural': 'Уровни подписки',
            },
        ),
        migrations.CreateModel(
            name='StreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IRL', 'IRL'), ('CREATION', 'CREATION'), ('ESPORTS', 'ESPORTS'), ('GAMING', 'GAMING'), ('MUSIC AND DJS', 'MUSIC AND DJS'), ('JUST CHATTING', 'JUST CHATTING')], max_length=50, unique=True, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('current_viewers', models.IntegerField(default=0, verbose_name='Текущее количество зрителей')),
                ('total_streams', models.IntegerField(default=0, verbose_name='Всего стримов')),
            ],
            options={
                'verbose_name': 'Категория стримов',
                'verbose_name_plural': 'Категории стримов',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Пользователь', max_length=30, verbose_name='Имя пользователя')),
                ('email', models.EmailField(default='user@example.com', max_length=100, verbose_name='Почта')),
                ('hash_particle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хэш')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Информация о себе')),
                ('avatar', models.ImageField(blank=True, default='users_photos/default_avatar.png', null=True, upload_to='users_photos/', verbose_name='Аватарка')),
                ('nickname', models.CharField(default='User', max_length=50, verbose_name='Никнейм')),
                ('roles', models.CharField(choices=[('Админ', 'Админ'), ('Модератор', 'Модератор'), ('Обычный пользователь', 'Обычный пользователь')], default='Обычный пользователь', max_length=50, verbose_name='Роль')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата подписки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата отписки')),
                ('auto_renewal', models.BooleanField(default=True, verbose_name='Авто продление')),
                ('id_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.level', verbose_name='Уровень')),
                ('id_users_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='hello.users', verbose_name='На кого подписались')),
                ('id_users_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='hello.users', verbose_name='Кто подписался')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый стрим', max_length=200, verbose_name='Название стрима')),
                ('status', models.CharField(choices=[('Транслируется', 'Транслируется'), ('Завершился', 'Завершился')], default='Транслируется', max_length=50, verbose_name='Статус')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='stream-preview/', verbose_name='Обложка')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала стрима')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания стрима')),
                ('max_viewers', models.IntegerField(blank=True, default=0, null=True, verbose_name='Макс. кол. зрителей')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание стрима')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.streamcategory', verbose_name='Категория')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стрим',
                'verbose_name_plural': 'Стримы',
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Сумма')),
                ('requisites', models.CharField(default='', max_length=24, verbose_name='Реквизиты')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание доната')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('id_users_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_donations', to='hello.users', verbose_name='Кто задонатил')),
                ('id_users_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to='hello.users', verbose_name='Кому задонатил')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
