# Generated by Django 5.2.6 on 2025-09-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Автор'},
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='namr',
            new_name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.CharField(default='No', verbose_name='Умер или нет'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='hello_autho_surname_eaffdc_idx'),
        ),
    ]
