# Generated by Django 5.2.6 on 2025-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.CharField(choices=[('Админ', 'Админ'), ('Модератор', 'Модератор'), ('Обычный пользователь', 'Обычный пользователь')], max_length=50, verbose_name='Роль'),
        ),
    ]
