# Generated by Django 5.2.6 on 2025-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_author_options_rename_namr_publisher_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='имя пользователя')),
                ('email', models.CharField(max_length=40, verbose_name='Почта')),
                ('hash_particle', models.TextField(verbose_name='Хэш')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('nickname', models.CharField(default='No', verbose_name='Никнейм')),
            ],
            options={
                'verbose_name': 'имя пользователя',
                'verbose_name_plural': 'имя пользователя',
                'ordering': ['id', 'user_name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
