# Generated by Django 5.2.6 on 2025-10-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_users_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания стрима'),
        ),
    ]
