# Generated by Django 5.2.6 on 2025-10-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_streams_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='max_viewers',
            field=models.IntegerField(blank=True, null=True, verbose_name='макс. кол. зрителей'),
        ),
    ]
