# Generated by Django 5.2.6 on 2025-09-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_users_remove_book_id_author_remove_book_id_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('requisites', models.CharField(max_length=24, verbose_name='Реквизиты')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('name', models.CharField(max_length=50, verbose_name='Название уровня')),
            ],
            options={
                'verbose_name': 'Уровень подписки',
                'verbose_name_plural': 'Уровни подписки',
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30, verbose_name='название ролей')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата подписки')),
                ('end_date', models.DateField(verbose_name='Дата отписки')),
                ('auto_renewal', models.BooleanField(verbose_name='Авто продление')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id', 'user_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='hash_particle',
            field=models.CharField(max_length=100, verbose_name='Хэш'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='No', max_length=50, verbose_name='Никнейм'),
        ),
        migrations.CreateModel(
            name='streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название стрима')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('start_time', models.TimeField(verbose_name='Время начала стрима')),
                ('end_time', models.TimeField(verbose_name='Время окончания стрима')),
                ('max_viewers', models.IntegerField(verbose_name='макс. кол. зрителей')),
                ('id_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.categories')),
                ('id_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.users')),
            ],
            options={
                'verbose_name': 'Стрим',
                'verbose_name_plural': 'Стримы',
            },
        ),
    ]
