# Generated by Django 5.2.6 on 2025-09-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_categories_donations_level_roles_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.roles', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='id_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.categories', verbose_name='Категрия'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='id_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.users', verbose_name='Пользователь'),
        ),
    ]
