# Generated by Django 5.2.6 on 2025-10-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_streams_max_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отписки'),
        ),
    ]
