# Generated by Django 5.2.6 on 2025-09-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_users_id_roles_alter_streams_id_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='id_users_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='hello.users', verbose_name='Кто задонатил'),
        ),
        migrations.AddField(
            model_name='donations',
            name='id_users_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='One', to='hello.users', verbose_name='Кому задонатил'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='id_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='id_users_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three', to='hello.users', verbose_name='На кого подписались'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='id_users_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='For', to='hello.users', verbose_name='Кто подписался'),
        ),
    ]
