# Generated by Django 5.2.7 on 2025-10-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_subscriptions_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='donations',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание доната'),
        ),
        migrations.AddField(
            model_name='streams',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='stream-preview/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о себе'),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Автарка'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('МИНОН', 'МИНОН'), ('МИНИМИНОН', 'МИНИМОНОН'), ('КУЛИЧ', 'КУЛИЧ'), ('МИНЬЁН', 'МИНЬЁН')], verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='status',
            field=models.CharField(choices=[('Транслируется', 'Транслируется'), ('Завершился', 'Завершился')], verbose_name='Статус'),
        ),
    ]
